[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools-git-versioning",
    "setuptools_scm"
]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true
