name: Teacher Helper CI/CD

on: push


jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    steps:

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/checkout@v2
      - name: test
        run: make test

  code_quality:
    name: black --check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: check
        run: make fmt-check

  deploy:
    name: Deploy to PyPi
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment: Deploy
    needs: [test, code_quality]
    steps:

      - uses: actions/checkout@v2
      - name: Build package
        run: make build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
