name: Teacher Helper CI/CD

on: push


jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    steps:

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/checkout@v2
      - name: test
        run: make test

  code_quality:
    name: black --check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: check
        run: make fmt-check

  # runs only for tagged commits
  docs-site:
    name: Deploy documentation website
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment: Kubernetes
    needs: [test, code_quality]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: jdevries3133
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup kube config
        run: mkdir ~/.kube && echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - name: Deploy documentation site
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make deploy-docs

  # runs only for tagged commits
  deploy:
    name: Deploy to PyPi
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment: Deploy
    needs: [test, code_quality]
    steps:

      - uses: actions/checkout@v2
      - name: Build package
        run: make build
      - name: Publish package and documentation site
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
